project:
  type: website

website:
  title: "Jaclyn Pham"
  navbar:
    left:
      - href: about.qmd
        text: About Me
      - href: blog.qmd
        text: My Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



